meta_product_name: "Gold Next Door"
meta_title: "Gold Next Door - Pirate For Life"
meta_description: "La piraterie est un art de vivre. Aussi monte à bord et échange avec ton crew les objets dont tu veux te séparer. Mais n'oublie pas: Tous les coups sont permis entre pirates"
meta_image: "Gold_Next_Door.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"
