meta_product_name: "Gold Next Door"
meta_title: "Gold Next Door - La piraterie n'est jamais finie"
meta_description: "Découvre des trésors cachés autour de toi jusqu'à aujourd'hui ! Dévoile les tiens pour savoir combien tu peux en tirer... Entre amis ou dans ton campus, qui sera le meilleur négociateur ?"
meta_image: "Gold_Next_Door.png"                       # should exist in `app/assets/images/`
twitter_account: "@goldnextdoor"
